parameter_defaults:
  NtpServer: '172.16.0.1'
  EC2MetadataIp: 172.16.0.1
  ControlPlaneDefaultRoute: 172.16.0.254
  ExternalInterfaceDefaultRoute: 192.168.0.1
  DnsServers: ["10.149.23.10"]

  NeutronNetworkType: 'geneve,vlan,flat'
  NeutronTunnelTypes: 'geneve,vlan,flat'
  NeutronNetworkVLANRanges: 'datacentre:1:1000' 
  BondInterfaceOvsOptions: "bond_mode=active-backup"
